// Generated by scripts/generate_product_galleries.mjs.
// Run npm run generate:product-galleries after changing product image files.

export const PRODUCT_GALLERY_IMAGES: Readonly<Record<string, readonly string[]>> = {
  "/images/products/MCB-AC-1P-01.jpg": [
    "/images/products/MCB-AC-1P-01.jpg",
    "/images/products/MCB-AC-1P-02.jpg",
    "/images/products/MCB-AC-1P-03.jpg",
    "/images/products/MCB-AC-1P-04.jpg",
    "/images/products/MCB-AC-1P-05.jpg",
    "/images/products/MCB-AC-1P-06.jpg",
    "/images/products/MCB-AC-1P-07.jpg"
  ],
  "/images/products/MCB-AC-2P-01.jpg": [
    "/images/products/MCB-AC-2P-01.jpg",
    "/images/products/MCB-AC-2P-02.jpg",
    "/images/products/MCB-AC-2P-03.jpg",
    "/images/products/MCB-AC-2P-04.jpg",
    "/images/products/MCB-AC-2P-05.jpg",
    "/images/products/MCB-AC-2P-06.jpg",
    "/images/products/MCB-AC-2P-07.jpg"
  ],
  "/images/products/MCB-AC-3P-01.jpg": [
    "/images/products/MCB-AC-3P-01.jpg",
    "/images/products/MCB-AC-3P-02.jpg",
    "/images/products/MCB-AC-3P-03.jpg",
    "/images/products/MCB-AC-3P-04.jpg",
    "/images/products/MCB-AC-3P-05.jpg",
    "/images/products/MCB-AC-3P-06.jpg",
    "/images/products/MCB-AC-3P-07.jpg"
  ],
  "/images/products/MCB-AC-4P-01.jpg": [
    "/images/products/MCB-AC-4P-01.jpg",
    "/images/products/MCB-AC-4P-02.jpg",
    "/images/products/MCB-AC-4P-03.jpg",
    "/images/products/MCB-AC-4P-04.jpg",
    "/images/products/MCB-AC-4P-05.jpg",
    "/images/products/MCB-AC-4P-06.jpg",
    "/images/products/MCB-AC-4P-07.jpg"
  ],
  "/images/products/MCB-DC-1P-01.jpg": [
    "/images/products/MCB-DC-1P-01.jpg",
    "/images/products/MCB-DC-1P-02.jpg",
    "/images/products/MCB-DC-1P-03.jpg",
    "/images/products/MCB-DC-1P-04.jpg",
    "/images/products/MCB-DC-1P-05.jpg",
    "/images/products/MCB-DC-1P-06.jpg",
    "/images/products/MCB-DC-1P-07.jpg"
  ],
  "/images/products/MCB-DC-2P-01.jpg": [
    "/images/products/MCB-DC-2P-01.jpg",
    "/images/products/MCB-DC-2P-02.jpg",
    "/images/products/MCB-DC-2P-03.jpg",
    "/images/products/MCB-DC-2P-04.jpg",
    "/images/products/MCB-DC-2P-05.jpg",
    "/images/products/MCB-DC-2P-06.jpg",
    "/images/products/MCB-DC-2P-07.jpg"
  ],
  "/images/products/MCB-DC-3P-01.jpg": [
    "/images/products/MCB-DC-3P-01.jpg",
    "/images/products/MCB-DC-3P-02.jpg",
    "/images/products/MCB-DC-3P-03.jpg",
    "/images/products/MCB-DC-3P-04.jpg",
    "/images/products/MCB-DC-3P-05.jpg",
    "/images/products/MCB-DC-3P-06.jpg",
    "/images/products/MCB-DC-3P-07.jpg"
  ],
  "/images/products/MCB-DC-4P-01.jpg": [
    "/images/products/MCB-DC-4P-01.jpg",
    "/images/products/MCB-DC-4P-02.jpg",
    "/images/products/MCB-DC-4P-03.jpg",
    "/images/products/MCB-DC-4P-04.jpg",
    "/images/products/MCB-DC-4P-05.jpg",
    "/images/products/MCB-DC-4P-06.jpg",
    "/images/products/MCB-DC-4P-07.jpg"
  ],
  "/images/products/SPD-AC-1P-Grey-1.jpg": [
    "/images/products/SPD-AC-1P-Grey-1.jpg",
    "/images/products/SPD-AC-1P-Grey-2.jpg",
    "/images/products/SPD-AC-1P-Grey-3.jpg",
    "/images/products/SPD-AC-1P-Grey-4.jpg",
    "/images/products/SPD-AC-1P-Grey-5.jpg",
    "/images/products/SPD-AC-1P-Grey-6.jpg",
    "/images/products/SPD-AC-1P-Grey-7.jpg"
  ],
  "/images/products/SPD-AC-2P-Grey-1.jpg": [
    "/images/products/SPD-AC-2P-Grey-1.jpg",
    "/images/products/SPD-AC-2P-Grey-2.jpg",
    "/images/products/SPD-AC-2P-Grey-3.jpg",
    "/images/products/SPD-AC-2P-Grey-4.jpg",
    "/images/products/SPD-AC-2P-Grey-5.jpg",
    "/images/products/SPD-AC-2P-Grey-6.jpg",
    "/images/products/SPD-AC-2P-Grey-7.jpg"
  ],
  "/images/products/SPD-AC-3P-Grey-1.jpg": [
    "/images/products/SPD-AC-3P-Grey-1.jpg",
    "/images/products/SPD-AC-3P-Grey-2.jpg",
    "/images/products/SPD-AC-3P-Grey-3.jpg",
    "/images/products/SPD-AC-3P-Grey-4.jpg",
    "/images/products/SPD-AC-3P-Grey-5.jpg",
    "/images/products/SPD-AC-3P-Grey-6.jpg",
    "/images/products/SPD-AC-3P-Grey-7.jpg"
  ],
  "/images/products/SPD-AC-4P-Grey-1.jpg": [
    "/images/products/SPD-AC-4P-Grey-1.jpg",
    "/images/products/SPD-AC-4P-Grey-2.jpg",
    "/images/products/SPD-AC-4P-Grey-3.jpg",
    "/images/products/SPD-AC-4P-Grey-4.jpg",
    "/images/products/SPD-AC-4P-Grey-5.jpg",
    "/images/products/SPD-AC-4P-Grey-6.jpg",
    "/images/products/SPD-AC-4P-Grey-7.jpg"
  ],
  "/images/products/SPD-DC-1P-White-1.jpg": [
    "/images/products/SPD-DC-1P-White-1.jpg",
    "/images/products/SPD-DC-1P-White-2.jpg",
    "/images/products/SPD-DC-1P-White-3.jpg",
    "/images/products/SPD-DC-1P-White-4.jpg",
    "/images/products/SPD-DC-1P-White-5.jpg",
    "/images/products/SPD-DC-1P-White-6.jpg",
    "/images/products/SPD-DC-1P-White-7.jpg",
    "/images/products/SPD-DC-1P-White-8.jpg"
  ],
  "/images/products/SPD-DC-2P-White-1.jpg": [
    "/images/products/SPD-DC-2P-White-1.jpg",
    "/images/products/SPD-DC-2P-White-2.jpg",
    "/images/products/SPD-DC-2P-White-3.jpg",
    "/images/products/SPD-DC-2P-White-4.jpg",
    "/images/products/SPD-DC-2P-White-5.jpg",
    "/images/products/SPD-DC-2P-White-6.jpg",
    "/images/products/SPD-DC-2P-White-7.jpg",
    "/images/products/SPD-DC-2P-White-8.jpg"
  ],
  "/images/products/SPD-DC-3P-White-1.jpg": [
    "/images/products/SPD-DC-3P-White-1.jpg",
    "/images/products/SPD-DC-3P-White-2.jpg",
    "/images/products/SPD-DC-3P-White-3.jpg",
    "/images/products/SPD-DC-3P-White-4.jpg",
    "/images/products/SPD-DC-3P-White-5.jpg",
    "/images/products/SPD-DC-3P-White-6.jpg",
    "/images/products/SPD-DC-3P-White-7.jpg",
    "/images/products/SPD-DC-3P-White-8.jpg"
  ],
  "/images/products/SPD-DC-4P-White-1.jpg": [
    "/images/products/SPD-DC-4P-White-1.jpg",
    "/images/products/SPD-DC-4P-White-2.jpg",
    "/images/products/SPD-DC-4P-White-3.jpg",
    "/images/products/SPD-DC-4P-White-4.jpg",
    "/images/products/SPD-DC-4P-White-5.jpg",
    "/images/products/SPD-DC-4P-White-6.jpg",
    "/images/products/SPD-DC-4P-White-7.jpg",
    "/images/products/SPD-DC-4P-White-8.jpg"
  ],
  "/images/products/SPD-DC-1P-Orange-1.jpg": [
    "/images/products/SPD-DC-1P-Orange-1.jpg",
    "/images/products/SPD-DC-1P-Orange-2.jpg",
    "/images/products/SPD-DC-1P-Orange-3.jpg",
    "/images/products/SPD-DC-1P-Orange-4.jpg",
    "/images/products/SPD-DC-1P-Orange-5.jpg",
    "/images/products/SPD-DC-1P-Orange-6.jpg",
    "/images/products/SPD-DC-1P-Orange-7.jpg",
    "/images/products/SPD-DC-1P-Orange-8.jpg"
  ],
  "/images/products/SPD-DC-2P-Orange-1.jpg": [
    "/images/products/SPD-DC-2P-Orange-1.jpg",
    "/images/products/SPD-DC-2P-Orange-2.jpg",
    "/images/products/SPD-DC-2P-Orange-3.jpg",
    "/images/products/SPD-DC-2P-Orange-4.jpg",
    "/images/products/SPD-DC-2P-Orange-5.jpg",
    "/images/products/SPD-DC-2P-Orange-6.jpg",
    "/images/products/SPD-DC-2P-Orange-7.jpg",
    "/images/products/SPD-DC-2P-Orange-8.jpg"
  ],
  "/images/products/SPD-DC-3P-Orange-1.jpg": [
    "/images/products/SPD-DC-3P-Orange-1.jpg",
    "/images/products/SPD-DC-3P-Orange-2.jpg",
    "/images/products/SPD-DC-3P-Orange-3.jpg",
    "/images/products/SPD-DC-3P-Orange-4.jpg",
    "/images/products/SPD-DC-3P-Orange-5.jpg",
    "/images/products/SPD-DC-3P-Orange-6.jpg",
    "/images/products/SPD-DC-3P-Orange-7.jpg",
    "/images/products/SPD-DC-3P-Orange-8.jpg"
  ],
  "/images/products/SPD-DC-4P-Orange-1.jpg": [
    "/images/products/SPD-DC-4P-Orange-1.jpg",
    "/images/products/SPD-DC-4P-Orange-2.jpg",
    "/images/products/SPD-DC-4P-Orange-3.jpg",
    "/images/products/SPD-DC-4P-Orange-4.jpg",
    "/images/products/SPD-DC-4P-Orange-5.jpg",
    "/images/products/SPD-DC-4P-Orange-6.jpg",
    "/images/products/SPD-DC-4P-Orange-7.jpg",
    "/images/products/SPD-DC-4P-Orange-8.jpg"
  ],
  "/images/products/RT18-32X-1P-1.jpg": [
    "/images/products/RT18-32X-1P-1.jpg",
    "/images/products/RT18-32X-1P-2.jpg",
    "/images/products/RT18-32X-1P-3.jpg",
    "/images/products/RT18-32X-1P-4.jpg",
    "/images/products/RT18-32X-1P-5.jpg",
    "/images/products/RT18-32X-1P-6.jpg",
    "/images/products/RT18-32X-1P-7.jpg"
  ],
  "/images/products/RT18-32X-2P-1.jpg": [
    "/images/products/RT18-32X-2P-1.jpg",
    "/images/products/RT18-32X-2P-2.jpg",
    "/images/products/RT18-32X-2P-3.jpg",
    "/images/products/RT18-32X-2P-4.jpg",
    "/images/products/RT18-32X-2P-5.jpg",
    "/images/products/RT18-32X-2P-6.jpg",
    "/images/products/RT18-32X-2P-7.jpg"
  ],
  "/images/products/RT18-32X-3P-1.jpg": [
    "/images/products/RT18-32X-3P-1.jpg",
    "/images/products/RT18-32X-3P-2.jpg",
    "/images/products/RT18-32X-3P-3.jpg",
    "/images/products/RT18-32X-3P-4.jpg",
    "/images/products/RT18-32X-3P-5.jpg",
    "/images/products/RT18-32X-3P-6.jpg",
    "/images/products/RT18-32X-3P-7.jpg"
  ],
  "/images/products/RT18-32X-4P-1.jpg": [
    "/images/products/RT18-32X-4P-1.jpg",
    "/images/products/RT18-32X-4P-2.jpg",
    "/images/products/RT18-32X-4P-3.jpg",
    "/images/products/RT18-32X-4P-4.jpg",
    "/images/products/RT18-32X-4P-5.jpg",
    "/images/products/RT18-32X-4P-6.jpg",
    "/images/products/RT18-32X-4P-7.jpg"
  ],
  "/images/products/RT18-63X-1P-1.jpg": [
    "/images/products/RT18-63X-1P-1.jpg",
    "/images/products/RT18-63X-1P-2.jpg",
    "/images/products/RT18-63X-1P-3.jpg",
    "/images/products/RT18-63X-1P-4.jpg",
    "/images/products/RT18-63X-1P-5.jpg",
    "/images/products/RT18-63X-1P-6.jpg",
    "/images/products/RT18-63X-1P-7.jpg"
  ],
  "/images/products/RT18-63X-2P-1.jpg": [
    "/images/products/RT18-63X-2P-1.jpg",
    "/images/products/RT18-63X-2P-2.jpg",
    "/images/products/RT18-63X-2P-3.jpg",
    "/images/products/RT18-63X-2P-4.jpg",
    "/images/products/RT18-63X-2P-5.jpg",
    "/images/products/RT18-63X-2P-6.jpg",
    "/images/products/RT18-63X-2P-7.jpg"
  ],
  "/images/products/RT18-63X-3P-1.jpg": [
    "/images/products/RT18-63X-3P-1.jpg",
    "/images/products/RT18-63X-3P-2.jpg",
    "/images/products/RT18-63X-3P-3.jpg",
    "/images/products/RT18-63X-3P-4.jpg",
    "/images/products/RT18-63X-3P-5.jpg",
    "/images/products/RT18-63X-3P-6.jpg",
    "/images/products/RT18-63X-3P-7.jpg"
  ],
  "/images/products/RT18-63X-4P-1.jpg": [
    "/images/products/RT18-63X-4P-1.jpg",
    "/images/products/RT18-63X-4P-2.jpg",
    "/images/products/RT18-63X-4P-3.jpg",
    "/images/products/RT18-63X-4P-4.jpg",
    "/images/products/RT18-63X-4P-5.jpg",
    "/images/products/RT18-63X-4P-6.jpg",
    "/images/products/RT18-63X-4P-7.jpg"
  ],
  "/images/products/RT18-125AM-1P-1.jpg": [
    "/images/products/RT18-125AM-1P-1.jpg"
  ],
  "/images/products/RT18-125AM-2p-1.jpg": [
    "/images/products/RT18-125AM-2p-1.jpg",
    "/images/products/RT18-125AM-2p-2.jpg",
    "/images/products/RT18-125AM-2p-3.jpg",
    "/images/products/RT18-125AM-2p-4.jpg",
    "/images/products/RT18-125AM-2p-5.jpg",
    "/images/products/RT18-125AM-2p-6.jpg"
  ],
  "/images/products/RT18-125AM-3p-1.jpg": [
    "/images/products/RT18-125AM-3p-1.jpg",
    "/images/products/RT18-125AM-3p-2.jpg",
    "/images/products/RT18-125AM-3p-3.jpg",
    "/images/products/RT18-125AM-3p-4.jpg",
    "/images/products/RT18-125AM-3p-5.jpg",
    "/images/products/RT18-125AM-3p-6.jpg"
  ],
  "/images/products/RT18-125AM-4p-1.jpg": [
    "/images/products/RT18-125AM-4p-1.jpg",
    "/images/products/RT18-125AM-4p-2.jpg",
    "/images/products/RT18-125AM-4p-3.jpg",
    "/images/products/RT18-125AM-4p-4.jpg",
    "/images/products/RT18-125AM-4p-5.jpg",
    "/images/products/RT18-125AM-4p-6.jpg"
  ],
  "/images/products/PN2-VA2-1.jpg": [
    "/images/products/PN2-VA2-1.jpg",
    "/images/products/PN2-VA2-2.jpg",
    "/images/products/PN2-VA2-3.jpg",
    "/images/products/PN2-VA2-4.jpg",
    "/images/products/PN2-VA2-5.jpg",
    "/images/products/PN2-VA2-6.jpg",
    "/images/products/PN2-VA2-7.jpg",
    "/images/products/PN2-VA2-8.jpg"
  ],
  "/images/products/PN2-VA3-1.jpg": [
    "/images/products/PN2-VA3-1.jpg",
    "/images/products/PN2-VA3-2.jpg",
    "/images/products/PN2-VA3-3.jpg",
    "/images/products/PN2-VA3-4.jpg",
    "/images/products/PN2-VA3-5.jpg",
    "/images/products/PN2-VA3-6.jpg",
    "/images/products/PN2-VA3-7.jpg",
    "/images/products/PN2-VA3-8.jpg"
  ],
  "/images/products/PN2-VA4-1.jpg": [
    "/images/products/PN2-VA4-1.jpg",
    "/images/products/PN2-VA4-2.jpg",
    "/images/products/PN2-VA4-3.jpg",
    "/images/products/PN2-VA4-4.jpg",
    "/images/products/PN2-VA4-5.jpg",
    "/images/products/PN2-VA4-6.jpg",
    "/images/products/PN2-VA4-7.jpg",
    "/images/products/PN2-VA4-8.jpg"
  ],
  "/images/products/PN2-VA5-1.jpg": [
    "/images/products/PN2-VA5-1.jpg",
    "/images/products/PN2-VA5-2.jpg",
    "/images/products/PN2-VA5-3.jpg",
    "/images/products/PN2-VA5-4.jpg",
    "/images/products/PN2-VA5-5.jpg",
    "/images/products/PN2-VA5-6.jpg",
    "/images/products/PN2-VA5-7.jpg",
    "/images/products/PN2-VA5-8.jpg"
  ],
  "/images/products/PN2-VAK-1.jpg": [
    "/images/products/PN2-VAK-1.jpg",
    "/images/products/PN2-VAK-2.jpg",
    "/images/products/PN2-VAK-3.jpg",
    "/images/products/PN2-VAK-4.jpg",
    "/images/products/PN2-VAK-5.jpg",
    "/images/products/PN2-VAK-6.jpg",
    "/images/products/PN2-VAK-7.jpg",
    "/images/products/PN2-VAK-8.jpg"
  ],
  "/images/products/PN2-VAFDM-1.jpg": [
    "/images/products/PN2-VAFDM-1.jpg",
    "/images/products/PN2-VAFDM-2.jpg",
    "/images/products/PN2-VAFDM-3.jpg",
    "/images/products/PN2-VAFDM-4.jpg",
    "/images/products/PN2-VAFDM-5.jpg",
    "/images/products/PN2-VAFDM-6.jpg",
    "/images/products/PN2-VAFDM-7.jpg",
    "/images/products/PN2-VAFDM-8.jpg"
  ],
  "/images/products/STATS-03-1.jpg": [
    "/images/products/STATS-03-1.jpg",
    "/images/products/STATS-03-2.jpg",
    "/images/products/STATS-03-3.jpg",
    "/images/products/STATS-03-4.jpg",
    "/images/products/STATS-03-5.jpg",
    "/images/products/STATS-03-6.jpg",
    "/images/products/STATS-03-7.jpg",
    "/images/products/STATS-03-8.jpg"
  ],
  "/images/products/STATS-04-1.jpg": [
    "/images/products/STATS-04-1.jpg",
    "/images/products/STATS-04-2.jpg",
    "/images/products/STATS-04-3.jpg",
    "/images/products/STATS-04-4.jpg",
    "/images/products/STATS-04-5.jpg",
    "/images/products/STATS-04-6.jpg",
    "/images/products/STATS-04-7.jpg",
    "/images/products/STATS-04-8.jpg"
  ],
  "/images/products/STATS-05-1.jpg": [
    "/images/products/STATS-05-1.jpg",
    "/images/products/STATS-05-2.jpg",
    "/images/products/STATS-05-3.jpg",
    "/images/products/STATS-05-4.jpg",
    "/images/products/STATS-05-5.jpg",
    "/images/products/STATS-05-6.jpg",
    "/images/products/STATS-05-7.jpg",
    "/images/products/STATS-05-8.jpg"
  ],
  "/images/products/STATS-06-1.jpg": [
    "/images/products/STATS-06-1.jpg",
    "/images/products/STATS-06-2.jpg",
    "/images/products/STATS-06-3.jpg",
    "/images/products/STATS-06-4.jpg",
    "/images/products/STATS-06-5.jpg",
    "/images/products/STATS-06-6.jpg",
    "/images/products/STATS-06-7.jpg",
    "/images/products/STATS-06-8.jpg"
  ],
  "/images/products/D52-2066-1.jpg": [
    "/images/products/D52-2066-1.jpg",
    "/images/products/D52-2066-2.jpg",
    "/images/products/D52-2066-3.jpg",
    "/images/products/D52-2066-4.jpg",
    "/images/products/D52-2066-5.jpg",
    "/images/products/D52-2066-6.jpg",
    "/images/products/D52-2066-7.jpg"
  ],
  "/images/products/D52-2066-wifi-1.jpg": [
    "/images/products/D52-2066-wifi-1.jpg",
    "/images/products/D52-2066-wifi-2.jpg",
    "/images/products/D52-2066-wifi-3.jpg",
    "/images/products/D52-2066-wifi-4.jpg",
    "/images/products/D52-2066-wifi-5.jpg",
    "/images/products/D52-2066-wifi-6.jpg",
    "/images/products/D52-2066-wifi-7.jpg",
    "/images/products/D52-2066-wifi-8.jpg"
  ],
  "/images/products/QY2P-1.jpg": [
    "/images/products/QY2P-1.jpg",
    "/images/products/QY2P-2.jpg",
    "/images/products/QY2P-3.jpg",
    "/images/products/QY2P-4.jpg",
    "/images/products/QY2P-5.jpg",
    "/images/products/QY2P-6.jpg",
    "/images/products/QY2P-7.jpg",
    "/images/products/QY2P-8.jpg"
  ],
  "/images/products/DDS-1.jpg": [
    "/images/products/DDS-1.jpg",
    "/images/products/DDS-2.jpg",
    "/images/products/DDS-3.jpg",
    "/images/products/DDS-4.jpg",
    "/images/products/DDS-5.jpg",
    "/images/products/DDS-6.jpg",
    "/images/products/DDS-7.jpg"
  ],
  "/images/products/ADD-1.jpg": [
    "/images/products/ADD-1.jpg",
    "/images/products/ADD-2.jpg",
    "/images/products/ADD-3.jpg",
    "/images/products/ADD-4.jpg",
    "/images/products/ADD-5.jpg",
    "/images/products/ADD-6.jpg",
    "/images/products/ADD-7.jpg"
  ],
  "/images/products/DDR-1.jpg": [
    "/images/products/DDR-1.jpg",
    "/images/products/DDR-2.jpg",
    "/images/products/DDR-3.jpg",
    "/images/products/DDR-4.jpg",
    "/images/products/DDR-5.jpg",
    "/images/products/DDR-6.jpg"
  ],
  "/images/products/SOLT-1.jpg": [
    "/images/products/SOLT-1.jpg",
    "/images/products/SOLT-2.jpg",
    "/images/products/SOLT-3.jpg",
    "/images/products/SOLT-4.jpg",
    "/images/products/SOLT-5.jpg",
    "/images/products/SOLT-6.jpg",
    "/images/products/SOLT-7.jpg",
    "/images/products/SOLT-8.jpg"
  ],
  "/images/products/SRP-1.jpg": [
    "/images/products/SRP-1.jpg",
    "/images/products/SRP-2.jpg",
    "/images/products/SRP-3.jpg",
    "/images/products/SRP-4.jpg",
    "/images/products/SRP-5.jpg",
    "/images/products/SRP-6.jpg"
  ],
  "/images/products/HT-8Way-2in1out-600VDC-1.jpg": [
    "/images/products/HT-8Way-2in1out-600VDC-1.jpg",
    "/images/products/HT-8Way-2in1out-600VDC-2.jpg",
    "/images/products/HT-8Way-2in1out-600VDC-3.jpg",
    "/images/products/HT-8Way-2in1out-600VDC-4.jpg",
    "/images/products/HT-8Way-2in1out-600VDC-5.jpg",
    "/images/products/HT-8Way-2in1out-600VDC-6.jpg"
  ],
  "/images/products/HT-8Way-1in1out-600VDC-1.jpg": [
    "/images/products/HT-8Way-1in1out-600VDC-1.jpg",
    "/images/products/HT-8Way-1in1out-600VDC-2.jpg",
    "/images/products/HT-8Way-1in1out-600VDC-3.jpg",
    "/images/products/HT-8Way-1in1out-600VDC-4.jpg",
    "/images/products/HT-8Way-1in1out-600VDC-5.jpg",
    "/images/products/HT-8Way-1in1out-600VDC-6.jpg"
  ],
  "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-1.jpg": [
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-1.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-2.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-3.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-4.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-5.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-32A-15AFUSE-6.jpg"
  ],
  "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-1.jpg": [
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-1.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-2.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-3.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-4.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-5.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-40A-20AFUSE-6.jpg"
  ],
  "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-1.jpg": [
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-1.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-2.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-3.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-4.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-5.jpg",
    "/images/products/HA-8Way-2in1out-500VDC-63A-30AFUSE-6.jpg"
  ],
  "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-1.jpg": [
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-1.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-2.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-3.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-4.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-5.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-32A-15AFUSE-6.jpg"
  ],
  "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-1.jpg": [
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-1.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-2.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-3.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-4.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-5.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-40A-20AFUSE-6.jpg"
  ],
  "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-1.jpg": [
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-1.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-2.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-3.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-4.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-5.jpg",
    "/images/products/HA-12Way-2in2out-500VDC-63A-30AFUSE-6.jpg"
  ],
  "/images/products/HA-4Way-500VDC-32A-1.jpg": [
    "/images/products/HA-4Way-500VDC-32A-1.jpg",
    "/images/products/HA-4Way-500VDC-32A-2.jpg",
    "/images/products/HA-4Way-500VDC-32A-3.jpg",
    "/images/products/HA-4Way-500VDC-32A-4.jpg",
    "/images/products/HA-4Way-500VDC-32A-5.jpg",
    "/images/products/HA-4Way-500VDC-32A-6.jpg"
  ],
  "/images/products/HA-4Way-500VDC-40A-1.jpg": [
    "/images/products/HA-4Way-500VDC-40A-1.jpg",
    "/images/products/HA-4Way-500VDC-40A-2.jpg",
    "/images/products/HA-4Way-500VDC-40A-3.jpg",
    "/images/products/HA-4Way-500VDC-40A-4.jpg",
    "/images/products/HA-4Way-500VDC-40A-5.jpg",
    "/images/products/HA-4Way-500VDC-40A-6.jpg"
  ],
  "/images/products/HA-8Way-1in1out-1000VDC-DS-1.jpg": [
    "/images/products/HA-8Way-1in1out-1000VDC-DS-1.jpg",
    "/images/products/HA-8Way-1in1out-1000VDC-DS-2.jpg",
    "/images/products/HA-8Way-1in1out-1000VDC-DS-3.jpg",
    "/images/products/HA-8Way-1in1out-1000VDC-DS-4.jpg",
    "/images/products/HA-8Way-1in1out-1000VDC-DS-5.jpg",
    "/images/products/HA-8Way-1in1out-1000VDC-DS-6.jpg"
  ],
  "/images/products/HA-12way-2in1out-1000VDC-DS-1.jpg": [
    "/images/products/HA-12way-2in1out-1000VDC-DS-1.jpg",
    "/images/products/HA-12way-2in1out-1000VDC-DS-2.jpg",
    "/images/products/HA-12way-2in1out-1000VDC-DS-3.jpg",
    "/images/products/HA-12way-2in1out-1000VDC-DS-4.jpg",
    "/images/products/HA-12way-2in1out-1000VDC-DS-5.jpg",
    "/images/products/HA-12way-2in1out-1000VDC-DS-6.jpg"
  ],
  "/images/products/HA-8Way-2DCB-2SPD-1.jpg": [
    "/images/products/HA-8Way-2DCB-2SPD-1.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-2.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-3.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-4.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-5.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-6.jpg"
  ],
  "/images/products/HA-4Way-1DCB-1SPD-White-1.jpg": [
    "/images/products/HA-4Way-1DCB-1SPD-White-1.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-2.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-3.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-4.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-5.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-6.jpg",
    "/images/products/HA-4Way-1DCB-1SPD-White-7.jpg"
  ],
  "/images/products/HA-8Way-2DCB-2SPD-White-1.jpg": [
    "/images/products/HA-8Way-2DCB-2SPD-White-1.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-2.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-3.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-4.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-5.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-6.jpg",
    "/images/products/HA-8Way-2DCB-2SPD-White-7.jpg"
  ],
  "/images/products/HA-18Way-4DCB-4SPD-White-1.jpg": [
    "/images/products/HA-18Way-4DCB-4SPD-White-1.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-2.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-3.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-4.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-5.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-6.jpg",
    "/images/products/HA-18Way-4DCB-4SPD-White-7.jpg"
  ],
  "/images/products/PCB-M6in-01-1.jpg": [
    "/images/products/PCB-M6in-01-1.jpg",
    "/images/products/PCB-M6in-01-2.jpg",
    "/images/products/PCB-M6in-01-3.jpg",
    "/images/products/PCB-M6in-01-4.jpg",
    "/images/products/PCB-M6in-01-5.jpg",
    "/images/products/PCB-M6in-01-6.jpg"
  ],
  "/images/products/PCB-M4in-02-1.jpg": [
    "/images/products/PCB-M4in-02-1.jpg",
    "/images/products/PCB-M4in-02-2.jpg",
    "/images/products/PCB-M4in-02-3.jpg",
    "/images/products/PCB-M4in-02-4.jpg",
    "/images/products/PCB-M4in-02-5.jpg",
    "/images/products/PCB-M4in-02-6.jpg"
  ],
  "/images/products/PCB-M6in-03-1.jpg": [
    "/images/products/PCB-M6in-03-1.jpg",
    "/images/products/PCB-M6in-03-2.jpg",
    "/images/products/PCB-M6in-03-3.jpg",
    "/images/products/PCB-M6in-03-4.jpg",
    "/images/products/PCB-M6in-03-5.jpg",
    "/images/products/PCB-M6in-03-6.jpg"
  ],
  "/images/products/PCB-M4in-04-1.jpg": [
    "/images/products/PCB-M4in-04-1.jpg",
    "/images/products/PCB-M4in-04-2.jpg",
    "/images/products/PCB-M4in-04-3.jpg",
    "/images/products/PCB-M4in-04-4.jpg",
    "/images/products/PCB-M4in-04-5.jpg",
    "/images/products/PCB-M4in-04-6.jpg",
    "/images/products/PCB-M4in-04-7.jpg"
  ],
  "/images/products/PCB-M6in-05-1.jpg": [
    "/images/products/PCB-M6in-05-1.jpg",
    "/images/products/PCB-M6in-05-2.jpg",
    "/images/products/PCB-M6in-05-3.jpg",
    "/images/products/PCB-M6in-05-4.jpg",
    "/images/products/PCB-M6in-05-5.jpg",
    "/images/products/PCB-M6in-05-6.jpg",
    "/images/products/PCB-M6in-05-7.jpg"
  ],
  "/images/products/ATS-ST-2P-63A(220V 110V)-1.jpg": [
    "/images/products/ATS-ST-2P-63A(220V 110V)-1.jpg",
    "/images/products/ATS-ST-2P-63A(220V 110V)-2.jpg",
    "/images/products/ATS-ST-2P-63A(220V 110V)-3.jpg",
    "/images/products/ATS-ST-2P-63A(220V 110V)-4.jpg",
    "/images/products/ATS-ST-2P-63A(220V 110V)-5.jpg",
    "/images/products/ATS-ST-2P-63A(220V 110V)-6.jpg"
  ],
  "/images/products/ATS-ST-4P-63A(220V 110V)-1.jpg": [
    "/images/products/ATS-ST-4P-63A(220V 110V)-1.jpg",
    "/images/products/ATS-ST-4P-63A(220V 110V)-2.jpg",
    "/images/products/ATS-ST-4P-63A(220V 110V)-3.jpg",
    "/images/products/ATS-ST-4P-63A(220V 110V)-4.jpg",
    "/images/products/ATS-ST-4P-63A(220V 110V)-5.jpg",
    "/images/products/ATS-ST-4P-63A(220V 110V)-6.jpg"
  ],
  "/images/products/ATS-W2R-2P(220V 110V)-1.jpg": [
    "/images/products/ATS-W2R-2P(220V 110V)-1.jpg",
    "/images/products/ATS-W2R-2P(220V 110V)-2.jpg",
    "/images/products/ATS-W2R-2P(220V 110V)-3.jpg",
    "/images/products/ATS-W2R-2P(220V 110V)-4.jpg",
    "/images/products/ATS-W2R-2P(220V 110V)-5.jpg",
    "/images/products/ATS-W2R-2P(220V 110V)-6.jpg"
  ],
  "/images/products/ATS-W2R-3P(220V 110V)-1.jpg": [
    "/images/products/ATS-W2R-3P(220V 110V)-1.jpg",
    "/images/products/ATS-W2R-3P(220V 110V)-2.jpg",
    "/images/products/ATS-W2R-3P(220V 110V)-3.jpg",
    "/images/products/ATS-W2R-3P(220V 110V)-4.jpg",
    "/images/products/ATS-W2R-3P(220V 110V)-5.jpg",
    "/images/products/ATS-W2R-3P(220V 110V)-6.jpg"
  ],
  "/images/products/ATS-W2R-4P(220V 110V)-1.jpg": [
    "/images/products/ATS-W2R-4P(220V 110V)-1.jpg",
    "/images/products/ATS-W2R-4P(220V 110V)-2.jpg",
    "/images/products/ATS-W2R-4P(220V 110V)-3.jpg",
    "/images/products/ATS-W2R-4P(220V 110V)-4.jpg",
    "/images/products/ATS-W2R-4P(220V 110V)-5.jpg",
    "/images/products/ATS-W2R-4P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ1-63-2P(220V 110V)-1.jpg": [
    "/images/products/STQ1-63-2P(220V 110V)-1.jpg",
    "/images/products/STQ1-63-2P(220V 110V)-2.jpg",
    "/images/products/STQ1-63-2P(220V 110V)-3.jpg",
    "/images/products/STQ1-63-2P(220V 110V)-4.jpg",
    "/images/products/STQ1-63-2P(220V 110V)-5.jpg",
    "/images/products/STQ1-63-2P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ1-63-3P(220V 110V)-1.jpg": [
    "/images/products/STQ1-63-3P(220V 110V)-1.jpg",
    "/images/products/STQ1-63-3P(220V 110V)-2.jpg",
    "/images/products/STQ1-63-3P(220V 110V)-3.jpg",
    "/images/products/STQ1-63-3P(220V 110V)-4.jpg",
    "/images/products/STQ1-63-3P(220V 110V)-5.jpg",
    "/images/products/STQ1-63-3P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ1-63-4P(220V 110V)-1.jpg": [
    "/images/products/STQ1-63-4P(220V 110V)-1.jpg",
    "/images/products/STQ1-63-4P(220V 110V)-2.jpg",
    "/images/products/STQ1-63-4P(220V 110V)-3.jpg",
    "/images/products/STQ1-63-4P(220V 110V)-4.jpg",
    "/images/products/STQ1-63-4P(220V 110V)-5.jpg",
    "/images/products/STQ1-63-4P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ2-63-2P(220V 110V)-1.jpg": [
    "/images/products/STQ2-63-2P(220V 110V)-1.jpg",
    "/images/products/STQ2-63-2P(220V 110V)-2.jpg",
    "/images/products/STQ2-63-2P(220V 110V)-3.jpg",
    "/images/products/STQ2-63-2P(220V 110V)-4.jpg",
    "/images/products/STQ2-63-2P(220V 110V)-5.jpg",
    "/images/products/STQ2-63-2P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ2-63-3P(220V 110V)-1.jpg": [
    "/images/products/STQ2-63-3P(220V 110V)-1.jpg",
    "/images/products/STQ2-63-3P(220V 110V)-2.jpg",
    "/images/products/STQ2-63-3P(220V 110V)-3.jpg",
    "/images/products/STQ2-63-3P(220V 110V)-4.jpg",
    "/images/products/STQ2-63-3P(220V 110V)-5.jpg",
    "/images/products/STQ2-63-3P(220V 110V)-6.jpg"
  ],
  "/images/products/STQ2-63-4P(220V 110V)-1.jpg": [
    "/images/products/STQ2-63-4P(220V 110V)-1.jpg",
    "/images/products/STQ2-63-4P(220V 110V)-2.jpg",
    "/images/products/STQ2-63-4P(220V 110V)-3.jpg",
    "/images/products/STQ2-63-4P(220V 110V)-4.jpg",
    "/images/products/STQ2-63-4P(220V 110V)-5.jpg",
    "/images/products/STQ2-63-4P(220V 110V)-6.jpg"
  ],
  "/images/products/Aerosol-Fire-Extinguishing-Sticker-1.jpg": [
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-1.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-2.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-3.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-4.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-5.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-6.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-7.jpg",
    "/images/products/Aerosol-Fire-Extinguishing-Sticker-8.jpg"
  ]
}
