import { readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = process.cwd()
const CATALOG_PATH = path.join(ROOT, 'lib', 'catalog-products.ts')
const PRODUCT_DIRECTORY = path.join(ROOT, 'public', 'images', 'products')
const OUTPUT_PATH = path.join(ROOT, 'lib', 'product-gallery-images.generated.ts')

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

async function main() {
  const [catalogSource, productFiles] = await Promise.all([
    readFile(CATALOG_PATH, 'utf8'),
    readdir(PRODUCT_DIRECTORY),
  ])

  const productImages = [
    ...new Set(
      [...catalogSource.matchAll(/"image":\s*"([^"]*\/images\/products\/[^"]+)"/g)].map(
        (match) => match[1]
      )
    ),
  ]

  if (productImages.length === 0 || productFiles.length === 0) {
    throw new Error('Product catalog or product image directory is empty; gallery manifest was not changed.')
  }

  const galleries = Object.fromEntries(
    productImages.map((productImage) => {
      const fileName = productImage.split('/').pop()
      const match = fileName?.match(/^(.*?)(\d+)(\.[a-zA-Z0-9]+)$/)

      if (!match) {
        return [productImage, [productImage]]
      }

      const [, prefix, , extension] = match
      const filePattern = new RegExp(
        `^${escapeRegExp(prefix)}(\\d+)${escapeRegExp(extension)}$`
      )
      const images = productFiles
        .map((item) => {
          const imageMatch = item.match(filePattern)
          return imageMatch
            ? { fileName: item, index: Number(imageMatch[1]) }
            : null
        })
        .filter(Boolean)
        .sort((a, b) => a.index - b.index)
        .map((item) => `/images/products/${item.fileName}`)

      return [productImage, images.length > 0 ? images : [productImage]]
    })
  )

  const output = `// Generated by scripts/generate_product_galleries.mjs.
// Run npm run generate:product-galleries after changing product image files.

export const PRODUCT_GALLERY_IMAGES: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(galleries, null, 2)}
`

  await writeFile(OUTPUT_PATH, output, 'utf8')
  console.log(
    `Generated ${Object.keys(galleries).length} product galleries in ${path.relative(ROOT, OUTPUT_PATH)}.`
  )
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
